- id: '1739957211186'
  alias: When start listening
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: when-start-listening-RuNGoCqwlJOAVNuOQtNxN-VW
  conditions: []
  actions: []
  mode: single
